#!/usr/bin/env bash

echo "pint pre commit hook start"

PHP_CS_FIXER="vendor/bin/pint"
HAS_PHP_CS_FIXER=false

# Skip for Merge
if git rev-parse -q --verify MERGE_HEAD; then
    echo "This is a merge commit. Skipping linting just in case it's a big one!"
    exit 0
fi

if [ -x $PHP_CS_FIXER ]; then
    HAS_PHP_CS_FIXER=true
fi

if $HAS_PHP_CS_FIXER; then
    FILES=`git status --porcelain | grep -E '^[AM] +(app|public|Tests|views).*\.php$' | cut -c 4- | tr '\n' ' '`
    if [ -z "$FILES" ]
	then
		  echo "No PHP files found in commit."
	else
		  echo ${FILES}
		  $PHP_CS_FIXER --config=pint.json ${FILES}
		  git add ${FILES}
	fi
else
    echo ""
    echo "Please install pint, e.g.:"
    echo ""
    echo "  composer require --dev laravel/pint"
    echo ""
    exit 1
fi

echo "pint pre commit hook finish"
